version: '2'

volumes:
  app-data: {}

services:
  django:
    build:
      context: .
      dockerfile: .docker/django/ci.Dockerfile
      args:
        - BUILD_ENVIRONMENT=production
    volumes:
      - "app-data:/app/data:z"
    env_file: .env
    restart: always

  nginx:
    build: .docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - django
    restart: always
