version: '2'

# docker-compose up --build -d
# docker-compose run django python manage.py migrate
# docker-compose run django python manage.py createsuperuser
# docker-compose run django python manage.py runjobs daily

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    volumes:
      - ./config/data:/app/config/data
    env_file: .env
    restart: always

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    ports:
      - "8080:80"
    restart: always
