version: '2'

volumes:
  app-data-local: {}

services:
  django-local:
    build:
      context: .
      dockerfile: .docker/django/Dockerfile
      args:
        - BUILD_ENVIRONMENT=local
    command: >
      python /app/samgrabby/manage.py runserver_plus 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ".:/app:z"
      - "app-data-local:/app/data:z"
    env_file: .env.local
