version: '2'

# docker-compose up --build -d
# docker-compose run django python manage.py migrate
# docker-compose run django python manage.py createsuperuser
# docker-compose run django python manage.py runjobs daily

volumes:
  app-data:

services:
  django:
    build:
      context: .
      dockerfile: .docker/django/Dockerfile
    volumes:
      - "app-data:/app/data"
    env_file: .env
    restart: always

  nginx:
    build: .docker/nginx
    depends_on:
      - django
    ports:
      - "8080:80"
    restart: always
