# Generated by Django 4.2.8 on 2024-01-02 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("soft", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="soft",
            options={
                "ordering": ["-upd_date"],
                "verbose_name": "Soft entry",
                "verbose_name_plural": "Soft entries",
            },
        ),
    ]
